---
title: "Grey Shield Research LLC - Services"
format: html
---

# Meet The Owner

Daniel Goldberg M.S. has over a decade in combined experience and education in criminal justice. As a former Correctional Officer with the Texas Department of Criminal Justice (TDCJ), Daniel knows what it is like to walk the tier and the realities of managing inmates. During his time in TDCJ, he worked primarily in General Population, however, he has experience in working in High Security, and Psychiatric settings. After working as a Correctional Officer, Daniel received his Masters of Science in Criminology from the University of Pennsylvania. After his time in Pennsylvania, he was an adjunct professor and research assistant the University of Central Florida, where he was also an editor's assistant at an academic journal, Corrections: Policy Practice and Research.

On his off time, he enjoys riding his motorcycle, reading, watching the Arizona Diamondbacks, and taking care of his beloved rabbits, Phoenix and Cowboy.

\[Replace with CV\]

## Simplified Educational Background

Associates of Science in Criminal Justice - Sacramento City College, Sacramento, CA

Bachelors of Science in Criminal Justice - West Texas Agricultural and Mechanical University, Canyon, TX

Masters of Science in Criminology - University of Pennsylvania, Philadelphia, PA

## Simplified Work Background

Correctional Officer IV - Texas Department of Criminal Justice

Adjunct Professor - University of Central Florida

Research Assistant - University of Central Florida

Research Scientist 2 - University of New Mexico's Institute for Social Research

Owner - Grey Shield Research LLC
